version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A stockproject worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        command: celery -A stockproject beat -l INFO 
        volumes:
          - .:/usr/src/app
        depends_on:
          - celery
          - django
          - pgdb
          - redis
        environment:
          - DJANGO_SETTINGS_MODULE=stockproject.settings
    pgdb:
        image: postgres:14
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=new_password
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine" 
volumes:
    pgdata:





