# Generated by Django 3.2.3 on 2022-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='lockindate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
