# Generated by Django 3.2.3 on 2022-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_userportfolio_lockindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
