# Generated by Django 3.2.3 on 2022-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userportfolio_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='lockindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
