# Generated by Django 3.2.3 on 2022-05-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTicker',
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
    ]
