# Generated by Django 3.2.3 on 2022-06-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='brokerageuserdob',
        ),
    ]
