# Generated by Django 3.2.3 on 2022-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_remove_userpreference_brokerageuserdob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='brokerageuserdob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
